import Banner from "@/components/banner/Banner";
import Navbar from "@/components/navbar/Navbar";
import TopNav from "@/components/navbar/TopNav";
// import { Barlow } from "next/font/google";
import Head from "next/head";

// const barlow = Barlow({
//   weights: [400, 500, 700],
//   styles: ["regular", "italic"],
// });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopNav />
        <Navbar />
        <Banner />
      </main>
    </>
  );
}
