import DiscourseSlack from "@/components/DiscourseSlack/DiscourseSlack";
import Footer from "@/components/Footer/Footer";
import SliderMain from "@/components/MonsonrySliders/SliderMain";
import Banner from "@/components/banner/Banner";
import CardSlider from "@/components/cardSlider/CardSlider";
import PerfectCloud from "@/components/perfectCloud/PerfectCloud";
import WhyPrefect from "@/components/whyPrefect/WhyPrefect";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <PerfectCloud />
        <SliderMain />
        <CardSlider />
        <WhyPrefect />
        <DiscourseSlack />
        <Footer />
      </main>
    </>
  );
}
